---
- name: Install required packages for openshift
  hosts: nodes
  remote_user: centos
  become: yes
  tasks:
    - name: Install NetworkManager
      yum:
        name: NetworkManager
        state: present
    - name: Install Redhat docker certificates
      yum:
        name: python-rhsm-certificates
        state: present
    - name: Install pyopenssl
      yum:
        name: pyopenssl
        state: present
    - name: Install htpasswd (httpd-tools)
      yum:
        name: httpd-tools
        state: present
    - name: Basic Packages
      yum:
        name: {{ item }}
        state: present
      with_items:
        - wget
        - git
        - net-tools
        - bind-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - vim
        - python-cryptography
        - pyOpenSSL.x86_64
        - python2-passlib
        - java-1.8.0-openjdk-headless
